version: '3.8'


services:

  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/db_data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgressheli
      - POSTGRES_DB=postgres_fastapi
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
